services:
  weight-tracker:
    image: ghcr.io/343max/weight-track
    ports:
      - "80:3000"
    environment:
      - APP_SECRET=${APP_SECRET}
      - DATABASE_PATH=/data/tracker.db
      - PORT=3001
    volumes:
      - ./data:/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/data?secret=${APP_SECRET}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    user: "1000:1000"
